baseURL = "https://yuyaichimura.com/"
languageCode = "en-us"
title = "Yuya Ichimura"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
# googleAnalytics = "{your tracking code}"

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "Yuya Ichimura"
    avatar = "yuya.jpg"
    # avatarDescription = "My avatar description"
    favicon = "favicon.ico"
    description = """
     Dev 
    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    taxonomy = ["JSON", "HTML"]

[[menu.main]]
    identifier = "linkedin"
    # name = "Twitter"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://linkedin.com/in/yuya-ichimura"

    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/yuyaichimura"
    weight = 30

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:yuyaichimura@gmail.com"
    weight = 40
