version: '3'

services:
  caddy:
    image: yuyaichimura/yuyaichimura.com
    ports:
      - 443:443
      - 80:80
    environment:
      - CADDYPATH=/etc/caddycerts
    volumes:
      - ./.caddy/:/etc/caddycerts/
      - ./logs/:/logs/
