version: '3'

services:
  caddy:
    image: "caddy"
    ports:
      - 443:443
      - 80:80
    environment:
      - CADDYPATH=/etc/caddycerts
    volumes:
      - ./public:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./.caddy/:/etc/caddycerts/
      - ./logs/:/logs/
