version: '3'

services:
  caddy:
    ports:
      - 8080:80
    volumes:
      - ./public:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./.caddy/:/etc/caddycerts/
      - ./logs/:/logs/
